### ISSUE TITLE
65PUS6703, MY2018

### ISSUE THREAD

**Issue by nseries100** [vniehues/homebridge-saphi-tv#15] opened 2021-07-23 10:34 UTC
Hi, I installed the hb plugin, then add my TV, which is 65PUS6703, it should be model year 2018. TV has Saphi OS. Firmware is up to date.

Unfortunately, plugin is not working, could you give me a hint? Some info below, Thx :)

homebridge config:
            {
            "name": "Saphi TV",
            "ip_adress": "192.168.1.21",
            "wol_adress": "wol://70:af:24:64:58:46",
            "has_tv_channels": true,
            "channel_setup_popup_time": 2250,
            "startup_time": 15,
            "timeout": 5,
            "input_delay": 650,
            "api_version": 6,
            "api_port_no": 1925,
            "protocol": "http",
            "polling_interval": 40,
            "has_ambilight": true,
            "has_ambihue": false,
            "ambi_poweroff": true,
            "ambi_poweron": false,
            "inputs": [
                {
                    "type": "TV"
                }
            ],
            "platform": "SaphiTV"
            }

homebridge log:
[23/07/2021, 11:25:35] [Saphi TV] set Active => 0
(node:6062) UnhandledPromiseRejectionWarning: FetchError: request to http://192.168.1.21:1925/6/input/key failed, reason: connect ECONNREFUSED 192.168.1.21:1925
    at ClientRequest.<anonymous> (/usr/lib/node_modules/homebridge-saphi-tv/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (events.js:375:28)
    at Socket.socketErrorListener (_http_client.js:475:9)
    at Socket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6062) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6062) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

nmap:
Starting Nmap 7.91 ( https://nmap.org ) at 2021-07-23 12:17 CEST
NSE: Loaded 153 scripts for scanning.
NSE: Script Pre-scanning.
Initiating NSE at 12:18
Completed NSE at 12:18, 0.00s elapsed
Initiating NSE at 12:18
Completed NSE at 12:18, 0.00s elapsed
Initiating NSE at 12:18
Completed NSE at 12:18, 0.00s elapsed
Initiating ARP Ping Scan at 12:18
Scanning 192.168.1.21 [1 port]
Completed ARP Ping Scan at 12:18, 0.09s elapsed (1 total hosts)
Initiating Parallel DNS resolution of 1 host. at 12:18
Completed Parallel DNS resolution of 1 host. at 12:18, 0.00s elapsed
Initiating SYN Stealth Scan at 12:18
Scanning 192.168.1.21 [65535 ports]
Discovered open port 56789/tcp on 192.168.1.21
Discovered open port 56790/tcp on 192.168.1.21
Discovered open port 13000/tcp on 192.168.1.21
Discovered open port 2870/tcp on 192.168.1.21
Completed SYN Stealth Scan at 12:18, 2.29s elapsed (65535 total ports)
Initiating Service scan at 12:18
Scanning 4 services on 192.168.1.21
Completed Service scan at 12:20, 128.65s elapsed (4 services on 1 host)
Initiating OS detection (try #1) against 192.168.1.21
NSE: Script scanning 192.168.1.21.
Initiating NSE at 12:20
Completed NSE at 12:20, 14.20s elapsed
Initiating NSE at 12:20
Completed NSE at 12:20, 1.04s elapsed
Initiating NSE at 12:20
Completed NSE at 12:20, 0.01s elapsed
Nmap scan report for 192.168.1.21
Host is up (0.00077s latency).
Not shown: 65531 closed ports
PORT      STATE SERVICE    VERSION
2870/tcp  open  upnp       IPI Media Renderer upnpd 1.0 (UPnP 1.0; DLNADOC 1.50)
13000/tcp open  unknown
56789/tcp open  tcpwrapped
56790/tcp open  tcpwrapped
MAC Address: 70:AF:24:64:58:46 (TP Vision Belgium NV)
Device type: general purpose
Running: Linux 3.X|4.X
OS CPE: cpe:/o:linux:linux_kernel:3 cpe:/o:linux:linux_kernel:4
OS details: Linux 3.2 - 4.9
Uptime guess: 3.173 days (since Tue Jul 20 08:11:50 2021)
Network Distance: 1 hop

**Comment by vniehues** [comment] 2021-07-23 11:06
Hey @nseries100 thank you for opening an issue. 

The error message shows that the TV refuses the connection on that IP. 
Please make sure that you've entered the correct IP and turn on your TV (with your normal remote). 
Then please go to the following "website": 
`http://192.168.178.21:1925/1/system`

and look for the following snippet and comment it here: 
```
"api_version": {
	"Major": 6,
	"Minor": 1,
	"Patch": 0
	},
```

If you cannot open that website it means that your TV is not reachable under that IP (at least not from the Device you are using to open the website). 
In that case please double-check your IP. 

Please let me know your findings. I'm sure we can make this work :)

**Comment by nseries100** [comment] 2021-07-23 12:16
Hi,

thank you for your quick response.

My IP seems to be correct. I attached some screenshots for you. TV shows in my UniFi controller and ping on that is also OK. But web url http://192.168.1.21:1925/1/system is not working .. :/

![Snímek obrazovky 2021-07-23 v 14 10 48](https://user-images.githubusercontent.com/35178228/126780282-c6673524-021e-46d5-bd68-b6de0e91185f.png)
![Snímek obrazovky 2021-07-23 v 14 12 02](https://user-images.githubusercontent.com/35178228/126780289-a3768296-520e-4371-a2bd-5d0447acf6f8.png)
![IMG_9179](https://user-images.githubusercontent.com/35178228/126780572-a9799d0d-bf55-40a2-9449-9b40c33de752.JPG)

**Comment by vniehues** [comment] 2021-07-23 13:00
Mhhh... 
Is Homebridge running on your MacMini? - If yes it should see the TV. 

Can you try to download the official App and test if that App can communicate with your TV?
https://apps.apple.com/be/app/philips-tv-remote-app/id1479155903

If the App can communicate with your TV the problem is probably in my plugin. 
If it can't communicate with your TV it's a problem with your local setup. (I had to enable some settings in my Unifi Controller for everything to work. I can try to find the settings for you.)

**Comment by nseries100** [comment] 2021-07-23 14:43
I tried the app you suggest and it cant find my TV :O 

HomeBridge is running on my raspberry pi 4 in my local network (192.168.1.14). Other plugins are working correctly. 

Could you find the specific settings for UniFi controller? My controller is running on UDM-PRO. 

Thank you for your help. 
![1E2B16A7-7524-4551-B650-4B2056FC7E93](https://user-images.githubusercontent.com/35178228/126799171-5972cf54-cae5-4ef7-9812-3f78e09d997b.png)

**Comment by vniehues** [comment] 2021-07-23 15:40
I turned on MultiCast DNS and IGMP Snooping and disabled Device Isolation on all my networks. 

I hope that helps! 

As it stands it seems like your TVs API is not reachable. 
You could try to google how to enable it. It might be disabled from the factory

**Comment by vniehues** [comment] 2021-07-23 15:50
Additionally you could test if one of the following urls works (api_version can be 1 to 6)
```
http://{your_tv_ip}:1925/{api_version}/system
http://{your_tv_ip}:1926/{api_version}/system
https://{your_tv_ip}:1925/{api_version}/system
https://{your_tv_ip}:1926/{api_version}/system
```

**Comment by nseries100** [comment] 2021-07-24 12:07
Hi there,

1/ i set unifi controller like you said (mDNS and IGMP snoop),
2/ i reset TV network setting (its on DHCP for now),
3/ some new TV fw update popped up today - so i installed it.

In Philips app, TV is now successfully paired.
When I tried the URL, its finally showed some info - attached in the end.

Unfortunately, WOL doesn't work.
The WoWlan setting in TV is active. MAC address in configuration is correct - verified in settings TV and UniFi. HB log says OK, but TV remains off.
[24/07/2021, 12:58:57] [Saphi TV] set Active => 1
[24/07/2021, 12:58:58] [Saphi TV] WOL-OK!

Any ideas? :)
---

{
	"menulanguage": "Czech",
	"name": "65PUS6703/12",
	"country": "Czechrep",
	"serialnumber_encrypted": "K2kseVsmQFgkd15gKkJ+aj2BjjBnxmFC2AWs5ZFovug=",
	"softwareversion_encrypted": "K2kseVsmQFgkd15gKkJ+ak3ednbEwu0L3RKYbs0Gj1xP4wabV+y2+BZ0IrujSFGi",
	"model_encrypted": "K2kseVsmQFgkd15gKkJ+aomwrvYy3DqdX0gO2ZbGsc4=",
	"deviceid_encrypted": "K2kseVsmQFgkd15gKkJ+arHnsgG500NWmsz4vGbw/kc=",
	"nettvversion": "4.6.0.1",
	"epgsource": "broadcast",
	"api_version": {
		"Major": 6,
		"Minor": 1,
		"Patch": 0
	},
	"featuring": {
		"jsonfeatures": {
			"recordings": [
				"List",
				"Schedule",
				"Manage"
			],
			"ambilight": [
				"Hue",
				"Ambilight"
			],
			"textentry": [
				"context_based",
				"initial_string_available"
			],
			"inputkey": [
				"key",
				"unicode"
			],
			"pointer": [
				"context_based"
			],
			"activities": [
				"browser"
			]
		},
		"systemfeatures": {
			"tvtype": "consumer",
			"content": [
				"dmr"
			],
			"pairing_type": "none",
			"os_type": "Linux"
		}
	}
}

**Comment by vniehues** [comment] 2021-07-24 14:07
That looks like a first success to me. Nice!

Can you turn on the TV with the Remote App?
 If yes, please try to install the beta version of my plugin using this command: 
`
sudo npm install -g homebridge-saphi-tv@beta
`
If you can't control it with the App you probably still have a problem in your network.

And then try to control your TV again. If that still doesn't work we need to look deeper. 

The output

```
[24/07/2021, 12:58:57] [Saphi TV] set Active => 1
[24/07/2021, 12:58:58] [Saphi TV] WOL-OK!
``` 
only means that the Plugin sent the command, not that the TV received it.

**Comment by nseries100** [comment] 2021-07-24 14:42
Yep, 
turning on by the Philips app is working correctly. 

I am noticing that "something happened" when i try to wol by homekit. My flash drive's led blinks a few times. But tv remains off. 

So I will try the beta version.

**Comment by vniehues** [comment] 2021-07-24 16:42
Did the beta version work better for you?

**Comment by nseries100** [comment] 2021-07-25 07:30
Installed the Beta now - it was with some warning, take a look:

homebridge@raspberrypi:/var/lib/homebridge $ sudo npm install -g homebridge-saphi-tv@beta

npm WARN fetch-timeout@0.0.2 requires a peer of node-fetch@^1.6.3 but none is installed. You must install peer dependencies yourself.

+ homebridge-saphi-tv@0.0.28-10
updated 2 packages in 29.941s


Should I install node fetch with "sudo npm install node-fetch --save" too?

Also the beta plugin not showing in Plugins in homebridge.

**Comment by vniehues** [comment] 2021-07-27 11:47
Sorry for the late response! 
Did you manage to get it to work? - I tried to replicate the error on a fresh homebridge install but it just worked.

**Comment by nseries100** [comment] 2021-07-27 12:26
Not yet.

I am not really sure what to do next. In HB plugins, I have only this plugin:

Homebridge Philips TV Saphi-OS
homebridge-saphi-tv v0.0.28-10

Should be there another one? (after running your install command for beta).

**Comment by vniehues** [comment] 2021-07-27 12:34
No that looks correct. 
Is homebridge starting normally?

Could you please try to remove your config and add a new one via the configuration ui?

**Comment by nseries100** [comment] 2021-07-27 12:39
1/ removed old config
2/ created new config using UI

{
            "name": "Philips TV",
            "ip_adress": "192.168.1.127",
            "wol_adress": "70:af:24:64:58:46",
            "has_tv_channels": true,
            "channel_setup_popup_time": 2250,
            "startup_time": 15,
            "timeout": 5,
            "input_delay": 650,
            "api_version": 6,
            "api_port_no": 1925,
            "protocol": "http",
            "polling_interval": 40,
            "has_ambilight": true,
            "multirow_apps": false,
            "vertical_inputs": false,
            "has_ambihue": false,
            "ambi_poweroff": true,
            "ambi_poweron": false,
            "platform": "SaphiTV"
 }

While HB loading there are some errors:

[27/07/2021, 13:37:46] [Philips TV] removing all accessories
[27/07/2021, 13:37:46] TypeError: Cannot read property 'filter' of undefined
    at new TelevisionAccessory (/usr/lib/node_modules/homebridge-saphi-tv/src/tvAccessory.ts:44:45)
    at SaphiTvPlatform.publishExampleExternalAccessory (/usr/lib/node_modules/homebridge-saphi-tv/src/platform.ts:64:5)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-saphi-tv/src/platform.ts:31:12)
    at HomebridgeAPI.emit (events.js:387:35)
    at HomebridgeAPI.signalFinished (/usr/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:173:14)

HB wont start.

**Comment by vniehues** [comment] 2021-07-27 12:51
Oh you found a bug! 
Please define at least one Input - that should eliminate this error.

I will fix that.

**Comment by nseries100** [comment] 2021-07-27 13:41
OK, I added input for Watch TV, see below.

Turning TV OFF - working
Turning TV ON - not working

In HomeKit, the state is shown wrong. TV is on, but HK saying is OFF.

config:
{
            "name": "Philips TV",
            "ip_adress": "192.168.1.127",
            "wol_adress": "70:af:24:64:58:46",
            "has_tv_channels": true,
            "channel_setup_popup_time": 2250,
            "startup_time": 15,
            "timeout": 5,
            "input_delay": 650,
            "api_version": 6,
            "api_port_no": 1925,
            "protocol": "http",
            "polling_interval": 40,
            "has_ambilight": true,
            "multirow_apps": false,
            "vertical_inputs": false,
            "has_ambihue": false,
            "ambi_poweroff": true,
            "ambi_poweron": false,
            "inputs": [
                {
                    "name": "Sledovat TV",
                    "type": "TV"
                }
            ],
            "platform": "SaphiTV"
        }

HB log:
[27/07/2021, 14:35:01] [Philips TV] Initializing SaphiTV platform...
[27/07/2021, 14:35:01] [Philips TV] Finished initializing platform: SaphiTV
[27/07/2021, 14:35:01] Loading 1 accessories...
[27/07/2021, 14:35:01] [Philips TV] Finished launching platform: SaphiTV

**[27/07/2021, 14:35:01] [Philips TV] removing all accessories
[Philips TV@@Manufacturer] characteristic value expected string and received object
[Philips TV Remote@@Manufacturer] characteristic value expected string and received object**

[27/07/2021, 14:35:01] [Philips TV] Publishing TV & Remote
Preparing Advertiser for 'Philips TV E7AC' using bonjour-hap backend!
Preparing Advertiser for 'Philips TV Remote 9744' using bonjour-hap backend!
Starting to advertise 'Philips TV E7AC' using bonjour-hap backend!
[27/07/2021, 14:35:01] Philips TV E7AC is running on port 41661.
[27/07/2021, 14:35:01] Please add [Philips TV E7AC] manually in Home app. Setup Code: 180-25-490
Starting to advertise 'Philips TV Remote 9744' using bonjour-hap backend!
[27/07/2021, 14:35:01] Philips TV Remote 9744 is running on port 44819.
[27/07/2021, 14:35:01] Please add [Philips TV Remote 9744] manually in Home app. 

**[27/07/2021, 15:05:35] [homebridge-saphi-tv] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[27/07/2021, 15:05:35] [homebridge-saphi-tv] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.
[27/07/2021, 15:05:35] [homebridge-saphi-tv] This plugin generated a warning from the characteristic 'On': characteristic value expected boolean and received undefined. See https://git.io/JtMGR for more info.**

**Comment by vniehues** [comment] 2021-07-27 14:24
Okay this is just a warning so everything should work. 
Please add the new TV to your home app and try to use it. 

If it still doesn't work we need to dig deeper.

**Comment by nseries100** [comment] 2021-07-28 06:13
Successfully added to homekit. 

Turning off working fine. 
Turning on still not working.

**Comment by vniehues** [comment] 2021-07-28 06:40
Since you can turn OFF the TV but not ON i think that the WOL MagicPaket gets lost on the way and does not reach the TV. 
Can you try the following commands on your Homebridge Server:
```
sudo apt-get install wakeonlan
wakeonlan 70:af:24:64:58:46
```

My plugin is sending 20 wol requests. That should be more than enough to wake every Device. 
WOL is not working properly on Philips TVs. Others have the same problems as you can [read here](https://github.com/eslavnov/pylips/issues/16#issuecomment-488034130)

**Comment by nseries100** [comment] 2021-07-28 09:53
Installed. Tried about 30times. TV is remaining in OFF state.

root@raspberrypi:/# wakeonlan 70:af:24:64:58:46
Sending magic packet to 255.255.255.255:9 with 70:af:24:64:58:46

**Comment by vniehues** [comment] 2021-07-28 13:52
In that case the problem is not with the plug-in itself but with your homebridge that can't reach the TV's MAC Adress. 
Earlier you said that there is a Network-Hop in your setup. I hunk that might be the reason. WOL is known to have problems with network hops.

**Comment by vniehues** [comment] 2021-07-28 13:58
Please have a look at this [Link](https://community.ui.com/questions/Solved-WOL-between-different-subnets/0551c2b3-0bc2-422e-b829-d168ff77a989). 
There are steps to enable WOL across different subnets on UniFi Devices. This might help you. 

I also use UniFi but I only have one subnet. 

Since this issue doesn't come from my plugin and I can't really help you (because I don't know any better) I will close this issue later today. 
If you think there is anything I can help you with please either reopen this issue or file a new one. 
Good luck! ☺️

**Comment by nseries100** [comment] 2021-07-28 14:16
There is no hop. I have only one subnet 192.168.1.x

**Comment by vniehues** [comment] 2021-07-28 14:31
Okay then I misunderstood your initial comment, sorry. 

I still believe that the issue is not my plugin since the normal WOL command also doesn't work. 

Is your RPie connected via wifi?

**Comment by nseries100** [comment] 2021-07-28 14:49
Its weird I know. 

Rpi is connected via lan cable. Philips tv too.

**Comment by vniehues** [comment] 2021-08-15 17:44
Hey @nseries100 did you manage to solve your network issues? I would like to create a small troubleshooting guide and I could list your steps there 🙂

**Comment by vniehues** [comment] 2021-08-19 07:08
If anyone encounters this problem, please open a new issue and we can have another go at it.

**Closed as completed by vniehues** 2021-08-19 07:08 UTC

**Comment by Thomas-Geraghty** [comment] 2021-09-08 08:52
Similar issues experienced by me in #17
